name: Tests

on: [push, pull_request]

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        moodle-branch: ['master', 'MOODLE_311_STABLE']
        php: ['8.0', '7.4']
        database: ['mysqli']
        include:
        - php: 7.4
          moodle-branch: MOODLE_310_STABLE
          database: mysqli
        - php: 7.4
          moodle-branch: MOODLE_39_STABLE
          database: mysqli

    steps:
      - name: checkout plugin
        uses: actions/checkout@v2
        with:
          path: this-plugin

      - name: setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, mysqli, gd, xmlrpc,zip
          ini-values: max_input_vars=5000

      - name: composer
        run: |
           composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3
           echo $(cd ci/bin; pwd) >> $GITHUB_PATH
           echo $(cd ci/vendor/bin; pwd) >> $GITHUB_PATH
           sudo locale-gen en_AU.UTF-8
           sudo systemctl start mysql.service

      - name: install Moodle
        run: moodle-plugin-ci install -v  --db-user=root --db-pass=root --db-host=127.0.0.1 --plugin this-plugin
        env:
          DB: ${{ matrix.database }}
          MOODLE_BRANCH: ${{ matrix.moodle-branch }}

      - name: phplint
        run: moodle-plugin-ci --ansi phplint

      - name: phpcpd
        run: moodle-plugin-ci --ansi phpcpd

      - name: phpmd
        run: moodle-plugin-ci --ansi phpmd

      - name: phpdoc
        run: moodle-plugin-ci --ansi phpdoc || true

      - name: codechecker
        run: moodle-plugin-ci --ansi codechecker

      - name: validate
        run: moodle-plugin-ci --ansi validate

      - name: savepoints
        run: moodle-plugin-ci --ansi savepoints

      - name: mustache
        run: moodle-plugin-ci --ansi mustache

      - name: grunt
        run: moodle-plugin-ci --ansi grunt

      - name: phpunit 
        run: moodle-plugin-ci --ansi phpunit || true

      - name: firefox
        run: moodle-plugin-ci --ansi behat
      
      - name: chrome
        run: moodle-plugin-ci --ansi behat --profile chrome

      - name: firefox classic
        run: moodle-plugin-ci --ansi behat --suite="classic"
      
      - name: chrome classic
        run: moodle-plugin-ci --ansi behat  --suite="classic" --profile chrome

      - name: admin bookmarks
        run: php admin/tool/behat/cli/run.php --profile=chrome --tags=@block_admin_bookmarks
        working-directory: moodle

      - name: privacy
        run: vendor/bin/phpunit --colors --no-coverage --testsuite tool_dataprivacy_testsuite,tool_policy_testsuite,core_privacy_testsuite
        working-directory: moodle
